server:
  port: 9091

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/vj-sonawane/config-server-microservice
          default-label: master

  application:
    name: CONFIG-SERVER